apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vprodb
  labels:
    app:  vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
    containers:
      - name:  vprodb
        image:  atangcho/vprofiledb:latest
        volumeMounts:
          - name: vpro-db-data 
            mountPath: /var/lib/mysql
        ports:
        - name: vprodb-port
          containerPort: 3306
          protocol: TCP
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: app-secret
                key: db-pass
    nodeselector:
        zone: us-east-1a
        volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0b532676b10e5ac06
            fstype: ext4
    initContainers:
      - name: busybox
        image: busybox:latest
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
        volumeMounts:
          - name:  vpro-db-data
            mountPath: /var/lib/mysql